-- Proyecto --
INSERT INTO PROYECTO (ID_PROYECTO, DURACION_DEL_SPRINT, NOMBRE_DE_PROYECTO, VELOCIDAD_DEL_EQUIPO) 
VALUES (1, 2, 'EXAMEN_FEBRERO_2017', 150);

-- Historias de Usuario --
INSERT INTO HISTORIA_DE_USUARIO (ID_HISTORIA_DE_USUARIO, DESCRIPCION, NOMBRE_DE_HISTORIA, USUARIO, VALOR_APORTADO, PROYECTO) 
VALUES (1, 'Historia 1, Examen Febrero 2017', 'Historia 1', 'USER_TEST_1', 30, 1);

INSERT INTO HISTORIA_DE_USUARIO (ID_HISTORIA_DE_USUARIO, DESCRIPCION, NOMBRE_DE_HISTORIA, USUARIO, VALOR_APORTADO, PROYECTO) 
VALUES (2, 'Historia 2, Examen Febrero 2017', 'Historia 2', 'USER_TEST_2', 20, 1);

INSERT INTO HISTORIA_DE_USUARIO (ID_HISTORIA_DE_USUARIO, DESCRIPCION, NOMBRE_DE_HISTORIA, USUARIO, VALOR_APORTADO, PROYECTO) 
VALUES (3, 'Historia 3, Examen Febrero 2017', 'Historia 3', 'USER_TEST_3', 10, 1);

-- Tareas Historia 1 --
INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (1, 'Tarea 1.1 --> Historia 1, Examen Febrero 2017', 90, 'Tarea 1.1', 5, 1);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (2, 'Tarea 1.2 --> Historia 1, Examen Febrero 2017', 90, 'Tarea 1.2', 4, 1);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (3, 'Tarea 1.3 --> Historia 1, Examen Febrero 2017', 60, 'Tarea 1.3', 2, 1);

-- Tareas Historia 2 --
INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (4, 'Tarea 2.1 --> Historia 2, Examen Febrero 2017', 95, 'Tarea 2.1', 5, 2);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (5, 'Tarea 2.2 --> Historia 2, Examen Febrero 2017', 55, 'Tarea 2.2', 4, 2);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (6, 'Tarea 2.3 --> Historia 2, Examen Febrero 2017', 30, 'Tarea 2.3', 4, 2);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (7, 'Tarea 2.4 --> Historia 2, Examen Febrero 2017', 40, 'Tarea 2.4', 2, 2);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (8, 'Tarea 2.5 --> Historia 2, Examen Febrero 2017', 50, 'Tarea 2.5', 2, 2);

-- Tareas Historia 3 --
INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (9, 'Tarea 3.1 --> Historia 3, Examen Febrero 2017', 60, 'Tarea 3.1', 5, 3);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (10, 'Tarea 3.2 --> Historia 3, Examen Febrero 2017', 40, 'Tarea 3.2', 4, 3);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (11, 'Tarea 3.3 --> Historia 3, Examen Febrero 2017', 20, 'Tarea 3.3', 3, 3);

INSERT INTO TAREA (ID_TAREA, DESCRIPCION, ESFUERZO, NOMBRE_DE_TAREA, PRIORIDAD, HISTORIA) 
VALUES (12, 'Tarea 3.4 --> Historia 1, Examen Febrero 2017', 80, 'Tarea 3.4', 2, 3);